In [1]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.18.0


In [2]:
# load a dataset
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 3s 0us/step


In [3]:
# build a machine learning model
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

c:\Users\KING\Miniconda3\envs\tf_env\lib\site-packages\keras\src\layers\reshaping\flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [4]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.35274068, -0.3338742 , -0.06910065,  0.19990684,  0.19410522,
         0.33877885,  0.53638947, -0.11182112, -0.10862985,  0.1620901 ]],
      dtype=float32)

In [5]:
tf.nn.softmax(predictions).numpy()

array([[0.06466354, 0.0658951 , 0.08587027, 0.11237542, 0.11172534,
        0.12911676, 0.15732722, 0.08227911, 0.08254211, 0.1082051 ]],
      dtype=float32)

In [6]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [7]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [8]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 3ms/step - accuracy: 0.8628 - loss: 0.4716
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9529 - loss: 0.1595
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9663 - loss: 0.1101
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9728 - loss: 0.0896
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - accuracy: 0.9757 - loss: 0.0784


In [9]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - 2ms/step - accuracy: 0.9743 - loss: 0.0821


[0.08208943158388138, 0.9743000268936157]

In [10]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [11]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.20949251e-08, 3.01038554e-08, 8.38712765e-07, 1.28011554e-04,
        1.04459896e-11, 2.50223646e-08, 5.22557766e-14, 9.99870658e-01,
        2.70335107e-07, 2.21568470e-07],
       [5.61233378e-07, 2.87925010e-03, 9.97021735e-01, 8.67299532e-05,
        3.94471592e-13, 1.06954958e-05, 1.83567650e-07, 1.15741812e-10,
        7.64500498e-07, 4.71584577e-12],
       [7.01815352e-08, 9.99266684e-01, 9.02751926e-05, 1.65781094e-05,
        1.49822745e-05, 3.39213648e-06, 7.32182480e-06, 5.19771536e-04,
        8.01256610e-05, 8.04272759e-07],
       [9.99652863e-01, 5.99032433e-08, 7.21563920e-05, 2.03570426e-06,
        7.38073311e-07, 9.76252777e-05, 1.26574669e-04, 4.40848598e-05,
        1.95769925e-08, 3.84574150e-06],
       [7.74330056e-06, 6.88154478e-10, 3.26994341e-05, 3.38534960e-08,
        9.96593416e-01, 3.87721677e-08, 6.78076731e-07, 6.24849417e-05,
        4.84055772e-06, 3.29802325e-03]], dtype=float32)>